markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 平沙落雁
host: http://hongmomanu.github.com
desc: 一琴一鹤走天涯.

custom:
    category:
        haskell: Haskell式编程
        dishaskell: 非Haskell编程
        linux: Linux相关 
        qin: 七弦益友       
    categories:
      - name:  haskell
        title: Haskell式编程

      - name:  dishaskell
        title: 非Haskell编程
      
      - name: linux
        title: Linux相关
      
      - name: qin
        title: 七弦益友 
        
meta:
    author:
        name: Jack
        email: hongmomanu@gmail.com
        disqus: hongmomanu              # Disqus缩略标识
        gcse: 010934958430114516510:WMX476786429     # Google自定义搜索标识ID
        github: hongmomanu                 # GitHub账号
        gravatar: 36f0bc2ba734853cb8fb90ae7dc0c1b2  # Gravatar头像标识

    disqus: go.disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
